// Copyright (c) 2017, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-2
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2018-03-09
:page-description: Explore how to use the new features in MicroProfile Config 2.0 specification to provide external configuration to microservices.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Externalizing configuration for Java microservices using Eclipse MicroProfile Config 2.0
:page-seo-description: A walkthough with examples on how to externalize configuration for Java microservices with the new features in Eclipse MicroProfile Config 2.0.
:guide-author: Open Liberty
= Configuring microservices using MicroProfile Config 2.0

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to provide external configuration to microservices with the new features in MicroProfile Config 2.0.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to externalize and inject static configuration properties for microservices using MicroProfile Config 2.0.

MicroProfile Config 2.0 is a major version release jam-packed with new features to help make building configurable microservices effortless.

You will learn to switch between different project environment using specific set of configuration properties for each environment, embed config property values inside of other config property values, retrieve details about a given config property, retrieve multi-valued config property values as a List, using the new built-in Converters, and inject related config property values with a shared prefix into a CDI bean.

The application that you will be working with is an `inventory` service which stores the information about various JVMs running on different hosts. Whenever a request is made to the `inventory` service to retrieve the JVM system properties of a particular host, the `inventory` service will communicate with the `system` service on that host to get these system properties. You will add configuration properties to simulate if a service is down for maintenance.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Configuring and Activating stage-specific Config Profile
// =================================================================================================
== Configuring and Activating stage-specific Config Profile

// file 0
pom.xml
[source, XML, linenums, role="code_column"]
----
include::finish/pom.xml[]
----

// file 1
server.xml
[source, XML, linenums, role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The MicroProfile Config 2.0 API is included in the MicroProfile 5.0 API artifact that is specified in your [hotspot file=0]`pom.xml` file. Look for the dependency with the [hotspot=microprofile file=0]`microprofile` artifact ID. This dependency provides a library that allows you to use the MicroProfile Config 2.0 API to externalize configurations for your microservices. The [hotspot=config file=1]`mpConfig` feature is also enabled in the [hotspot file=1]`src/main/liberty/config/server.xml` file, along with the [hotspot=cdi file=1]`cdi` feature to enable all the injection functionally.

Config Profiles allow configuration for different environments and project phases such as dev, testing, prod, etc. while only a single profile is active. The active Config Profile is specified via the property `mp.config.profile`, which can be set in any of the configuration sources. Once it is set, the corresponding set of configuration properties associated with the active profile are used. 

It can also be set at your application startup. The `finish` directory in the root of this guide contains the finished application. Try out the application in the maintenance mode by setting the Config Profile as `maintaining` when starting your application.

// tag::runCommand[]
To try out the application, first go to the `finish` directory and run the following Maven goal to build the application and deploy it to Open Liberty:

[role='command']
```
cd finish
mvn liberty:run -Dliberty.var.mp.config.profile="maintaining"
```

After you see the following message, your application server is ready:

[role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----
// end::runCommand[]

The `-Dliberty.var.mp.config.profile` argument sets a https://maven.apache.org/pom.html#Properties[Maven property^] which the [hotspot=liberty-maven-plugin file=0]`liberty-maven-plugin` https://github.com/scottkurz/ci.maven/blob/f3920800351b6d2c26e62a19008b68093afa48ea/docs/common-server-parameters.md#setting-liberty-configuration-with-maven-project-properties[uses to update the Liberty configuration^]. In this case, the `mp.config.profile property` is set to `maintaining`.

You can access the following two microservices to test their availability:

* http://localhost:9080/system/properties

* http://localhost:9080/inventory/systems 

Since you started the application in the `maintaining` environment, both services return the message `... Service is currently down for maintenance ...`.

[role=command]
include::{common-includes}/twyb-end.adoc[]

// static guide instructions:
Now, navigate to the `start` directory to begin.

[role=command]
include::{common-includes}/devmode-lmp33-start.adoc[]

// file 2
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[]
----

The active Config Profile is specified as [hotspot=config-profile file=2]`maintaining` in the [hotspot file=2]`META-INF/microprofile-config.properties` property file, the default configuration source for an application that uses MicroProfile Config.

=== Externalizing property on Property level

// file 0
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[]
----

A configuration property can be used at the property level by setting its name in the format: `%<mp.config.profile>.<original property name>`. 

Navigate to the [hotspot file=0]`microprofile-config.properties` property file. With `mp.config.profile` set to `maintaining`, retrieving the config value for `io_openliberty_guides.system_inMaintenance` would use the config property [hotspot=system-inMaintenance file=0]`%maintaining.io_openliberty_guides.system_inMaintenance`. The value of the property would resolve to `true`.

=== Externalizing property on Config Source level

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `microprofile-config-maintaining.properties` file.#
`src/main/resources/META-INF/microprofile-config-maintaining.properties`
----

// file 0
microprofile-config-maintaining.properties
[source, properties, linenums, role='code_column hide_tags=role,tech-support,customer-support,email2,maintenanceWindow,downtime']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaining.properties[]
----

// file 1
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[]
----

Config Profile properties can be used at the Config Source level by providing a config source file under the META-INF folder on the classpath with the name formatted as `microprofile-config-<mp.config.profile>.properties`. 

With `mp.config.profile` set to `maintaining`, the file [hotspot file=0]`microprofile-config-maintaining.properties` would be loaded be loaded on top of the default config source [hotspot file=1]`microprofile-config.properties` file. In this case, the [hotspot=inventory-inMaintenance file=0]`io_openliberty_guides.inventory_inMaintenance` property from [hotspot file=0]`microprofile-config-maintaining.properties` would take precedence, and thus is set to `true`.

// =================================================================================================
// Working with Property Expressions
// =================================================================================================
== Working with Property Expressions

The value of a config property may contain an expression corresponding to another config property. Property Expressions provide a way to embed expression segments in property values using the `${}` sequence.

Additionally, you can implement expressions with the following syntax:

* `${prop:default}` - Provides a `default` value after the `:` if the expression doesn't find a value for the property `prop`.

* `${prop${compose}}` - Composed expressions where inner expressions are resolved first.

* `${prop1}${prop2}` - Multiple expressions.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-maintaining.properties` file.#
`src/main/resources/META-INF/microprofile-config-maintaining.properties`
----

// file 0
microprofile-config-maintaining.properties
[source, Properties, linenums, role='code_column hide_tags=email1,maintenanceWindow,downtime']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaining.properties[]
----

When looking up the [hotspot=email2 file=0]`io_openliberty_guides.email` property, the value is expanded to `alice@guides.openliberty.io`.

Try changing the configuration value for property [hotspot=role file=0]`role` in the [hotspot file=0]`microprofile-config-maintaining.properties` file. Your changes are updated dynamically, and you do not need to restart the server. Refresh http://localhost:9080/config to observe the value of property [hotspot=email2 file=0]`io_openliberty_guides.email` at each change:

* Update the value of property [hotspot=role file=0]`role` to `customerSupport`. The value of `io_openliberty_guides.email` is resolved to `bob@guides.openliberty.io`.

* Update the value of property [hotspot=role file=0]`role` to `foo`. Since property `io_openliberty_guides.foo` does not exist, the deafult value `admin` is used. The value of `io_openliberty_guides.email` is then resolved to `admin@guides.openliberty.io`.

When you are finished trying out changing this configuration, change the value of property [hotspot=role file=0]`role` back to `technicalSupport`.

// =================================================================================================
// Injecting configuration using the ConfigValue metadata object
// =================================================================================================
== Injecting configuration using the ConfigValue metadata object

// file 0
microprofile-config-maintaining.properties
[source, Properties, linenums, role='code_column hide_tags=email1,maintenanceWindow,downtime']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaining.properties[]
----

// file 1
bootstrap.properties
[source, Properties, linenums, role='code_column']
----
include::finish/src/main/liberty/config/bootstrap.properties[]
----

// file 2
jvm.options
[source, Options, linenums, role='code_column']
----
include::finish/src/main/liberty/config/jvm.options[]
----

// file 3
server.xml
[source, XML, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

Note that the `io_openliberty_guides.technical_support` property is defined in multiple different config sources in the application as listed as follows:

Note that the following five config sources all contain the `io_openliberty_guides.technical_support` property:

* [hotspot=tech-support file=0]`microprofile-config-maintaining.properties`

* [hotspot=tech-support file=1]`bootstrap.properties`

* [hotspot=tech-support file=2]`jvm.options`

* [hotspot=tech-support file=3]`server.xml`

To figure out where the value of property `io_openliberty_guides.technical_support` comes from, 

[role="code_command hotspot file=4", subs="quotes"]
----
#Replace the `ConfigResource.java` file.#
`src/main/java/io/openliberty/guides/config/ConfigResource.java`
----

// file 4
ConfigResource.java
[source, java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/config/ConfigResource.java[]
----

The ConfigValue holds additional information after the lookup of a configuration property.

To use the https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/ConfigValue.html[ConfigValue API class^], inject the [hotspot=tech-support file=4]`io_openliberty_guides.technical_support` property as usual, only this time define the type as `ConfigValue`.

The `ConfigValue` holds additional information after the lookup of a config property, where you can retrieve with the get methods defined in the https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/[Javadoc^].

For example, the [hotspot=getConfigSource file=4]`getConfigSource()` method determines which ConfigSource has the highest ordinal for property `io_openliberty_guides.technical_support` by calling the [hotspot=getSourceName file=4]`getSourceName()` method.

Now point your browser to http://localhost:9080/config/technicalSupport to determine the winning ConfigSource for property `io_openliberty_guides.technical_support`. Try changing the value of property `io_openliberty_guides.technical_support` in the winning ConfigSource and observe the changes at http://localhost:9080/config.

// =================================================================================================
// Injecting multi-valued config property using Config API
// =================================================================================================
== Injecting multi-valued config property using Config API

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-maintaining.properties` file.#
`src/main/resources/META-INF/microprofile-config-maintaining.properties`
----

// file 0
microprofile-config-maintaining.properties
[source, Properties, linenums, role='code_column hide_tags=email1']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaining.properties[]
----

Note that property [hotspot=maintenanceWindow file=0]`io_openliberty_guides.maintenanceWindow` is defined with multiple values, seperated by comma. 

To retrieve the values from this multi-valued config property as a List,

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `InventoryConfig.java` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
----

// file 1
InventoryConfig.java
[source, java, linenums, role='code_column hide_tags=inject-downtime,getDowntime']
----
include::finish/module-multi-valued/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[]
----

Inject a [hotspot=config file=1]`Config` instance to use the https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/Config.html[Config API^] methods. The [hotspot=getOptionalValues file=1]`getOptionalValues()` method returns the resolved property values for the specified `propertyName` with the specified `propertyType`. In this case, when retrieving property [hotspot=maintenanceWindow file=0]`io_openliberty_guides.maintenanceWindow`, an [hotspot=getOptionalValues file=1]`Optional<List<Integer>>` type is returned.

You can also retrieve values natively, without Optionals, using the https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/Config.html#getValues-java.lang.String-java.lang.Class-[Config.getValues()^] method.

// =================================================================================================
// Using the new built-in Converters
// =================================================================================================
== Using the new built-in Converters

// file 0
InventoryConfig.java
[source, Java, linenums, role='code_column']
----
include::finish/module-multi-valued/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[]
----

// file 1
microprofile-config-maintaining.properties
[source, Properties, linenums, role='code_column hide_tags=email1']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaining.properties[]
----

MicroProfile Config 2.0 API now provides `OptinalInt`, `OptionalLong` and `OptionalDouble` as https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/spi/Converter.html#built_in_converters[built-in Converters^]. You can convert injected config property values to a defined type with the new Converters like any of the existing built-in Converters.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `InventoryConfig.java` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
----

The [hotspot=downtime file=0]`io_openliberty_guides.downtime` property is declared as type [hotspot=downtime file=1]`OptinalInt`. 

Properties are optional when the annotation specify an optional default value. In this case, the `OptionalInt` Converter converts the value of property [hotspot=downtime file=0]`io_openliberty_guides.downtime` to `null` as the default value. This allows its value to be retrieve "optionally". That is, when the configuration property value is not found in any of the ConfigSources in the current runtime environment, an `Optional.empty` value will be returned instead of a `NoSuchElementException`. 

// =================================================================================================
// Injecting related properties through @ConfigProperties annotation
// =================================================================================================
== Injecting related properties through @ConfigProperties annotation

MicroProfile Config 2.0 provides a way to aggregate configuration properties starting with the same prefix into a single property class through the `@ConfigProperties` annotation.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `ConfigDetailsBean.java` class.#
`src/main/java/io/openliberty/guides/config/ConfigDetailsBean.java`
----

// file 0
ConfigDetailsBean.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/config/ConfigDetailsBean.java[]
----

Define a CDI bean for config properties which share the common prefix `io_openliberty_guides`.

The [hotspot=ConfigProperties file=0]`@ConfigProperties` annotation retrieves the properties prefixed by `io_openliberty_guides` into a single property class called [hotspot=ConfigDetailsBean file=0]`ConfigDetailsBean`.

To inject the bean annotated with `@ConfigProperties`, 

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `InventoryConfig.java` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryConfig.java`
----

// file 1
InventoryConfig.java
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryConfig.java[]
----

The changes introduced here use the [hotspot=Inject file=1]`@Inject` and the [hotspot=ConfigProperties file=1]`@ConfigProperties` annotations to inject the [hotspot=ConfigDetailsBean file=0]`ConfigDetailsBean` property class into the [hotspot file=1]`InventoryConfig` class.

// =================================================================================================
// Running the application
// =================================================================================================

[role=command]
include::{common-includes}/devmode-build.adoc[]

While the server is running, the following two microservices should be available to access:

* http://localhost:9080/system/properties

* http://localhost:9080/inventory/systems

Since you set the Config Profile to the `maintaining` environment, the following message displays when accessing both services: `... Service is currently down for maintenance ...`.

You can find the service that retrieves configuration information that is specific to this guide at the following location:

* http://localhost:9080/config

// file 0
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[]
----

Play with this application by changing configuration values for the properties in the Config Sources. Your changes are added dynamically, and you do not need to restart the server. Refresh the above URLs to see the dynamic changes.

For example, delete or comment out property [hotspot=config-profile file=0]`mp.config.profile`, then try to access the two microservices again. Each service now returns a valid response.

// =================================================================================================
// Testing the application
// =================================================================================================
== Testing the application

[role="code_command hotspot", subs="quotes"]
----
#Create the `ConfigurationIT` class.#
`src/test/java/it/io/openliberty/guides/config/ConfigurationIT.java`
----

// file 0
ConfigurationIT.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationIT.java[]
----

// file 1
microprofile-config.properties
[source, Properties, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/resources/META-INF/microprofile-config.properties[]
----

// microprofile-config.properties
// [source, properties, linenums, role='code_column']
// ----
// include::finish/src/main/resources/META-INF/microprofile-config.properties[]
// ----

The integration test reads the value of the [hotspot=config-profile file=1]`mp.config.profile` configuration property in the `META-INF/microprofile-config.properties` to check the active Config Profile before running the test cases.

The [hotspot=testConfigTechnicalSupport file=0]`testConfigTechnicalSupport()` test case checks the HTTP response of the `config/technicalSupport` endpoint.

The [hotspot=testInventoryServiceStatus file=0]`testInventoryServiceStatus()` checks the HTTP response of the `inventory` service. If [hotspot=config-profile file=1]`mp.config.profile` is set to `maintaining`, the service returns a Service Unavailable server error response code. Otherwise, the service returns a valid response.

The [hotspot=testSystemServiceStatus file=0]`testSystemServiceStatus()` checks the HTTP response of the `system` service. If [hotspot=config-profile file=1]`mp.config.profile` is set to `maintaining`, the service returns a Service Unavailable server error response code. Otherwise, the service returns a valid response.

In addition, a few endpoint tests have been provided for you to test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you must have introduced a bug into the code. These tests run automatically as a part of the integration test suite.

[role=command]
include::{common-includes}/devmode-test.adoc[]

You see the following output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.config.ConfigurationIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.516 s - in it.io.openliberty.guides.config.ConfigurationIT
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in it.io.openliberty.guides.system.SystemEndpointIT
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results:

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
----

If you run the test without specifying the [hotspot=config-profile file=1]`mp.config.profile` property, you will see warning and error messages which are expected and result from a request to a bad or an unknown hostname. This request is made in the `testUnknownHost()` test from the `InventoryEndpointIT` integration test.

[role=command]
include::{common-includes}/devmode-quit.adoc[]


== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config in Open Liberty.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]
