// Copyright (c) 2017, 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-2
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2018-03-09
:page-description: Explore how to use the new features in MicroProfile Config 2.0 specification to provide external configuration to microservices.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Externalizing configuration for Java microservices using Eclipse MicroProfile Config 2.0
:page-seo-description: A walkthough with examples on how to externalize configuration for Java microservices with the new features in Eclipse MicroProfile Config 2.0.
:guide-author: Open Liberty
= Configuring microservices using MicroProfile Config 2.0

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to provide external configuration to microservices with the new features in MicroProfile Config 2.0.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how to externalize and inject static configuration properties for microservices using MicroProfile Config 2.0.

MicroProfile Config 2.0 is a major version release jam-packed with new features to help make building configurable microservices effortless.

You will learn to switch between different project phases using specific set of configuration properties for each phase, embed config property values inside of other config property values, retrieve details about a given config property, retrieve multi-valued config property values as a List, and inject related config property values with a shared prefix into a CDI bean.

The application that you will be working with is an `inventory` service which stores the information about various JVMs running on different hosts. Whenever a request is made to the `inventory` service to retrieve the JVM system properties of a particular host, the `inventory` service will communicate with the `system` service on that host to get these system properties. You will add configuration properties to simulate if a service is down for maintenance.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Specifying Config Profile
// =================================================================================================
== Activating stage-specific Config Profile

// static guide instructions:
Now, navigate to the `start` directory to begin.

// file 0
pom.xml
[source, XML, linenums, role="code_column"]
----
include::finish/pom.xml[]
----

// file 1
server.xml
[source, XML, linenums, role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The MicroProfile Config 2.0 API is included in the MicroProfile 5.0 API artifact that is specified in your [hotspot file=0]`pom.xml` file. Look for the dependency with the [hotspot=microprofile file=0]`microprofile` artifact ID. This dependency provides a library that allows you to use the MicroProfile Config 2.0 API to externalize configurations for your microservices. The [hotspot=config file=1]`mpConfig` feature is also enabled in the [hotspot file=1]`src/main/liberty/config/server.xml` file, along with the [hotspot=cdi file=1]`cdi` feature to enable all the injection functionally.

Config Profiles allow configuration for different environments and project phases such as dev, testing, prod, etc. while only a single profile is active. The active Config Profile is specified via the property `mp.config.profile`, which can be set in any of the configuration sources or at application startup. Once it is set, the corresponding set of configuration properties associated with the active profile are used. 

When you run Open Liberty in development mode, known as dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following goal to start Open Liberty in dev mode with the `maintaining` environment:

[role=command]
```
mvn liberty:dev -Dliberty.var.mp.config.profile="maintaining"
```

After you see the following message, your application server in dev mode is ready:

[role="no_copy"]
----
**************************************************************
*    Liberty is running in dev mode.
----

Dev mode holds your command-line session to listen for file changes. Open another command-line session to continue, or open the project in your editor.

The `-Dliberty.var.mp.config.profile` argument sets a https://maven.apache.org/pom.html#Properties[Maven property^] which the [hotspot=liberty-maven-plugin file=0]`liberty-maven-plugin` https://github.com/scottkurz/ci.maven/blob/f3920800351b6d2c26e62a19008b68093afa48ea/docs/common-server-parameters.md#setting-liberty-configuration-with-maven-project-properties[uses to update the Liberty configuration^]. In this case, the `mp.config.profile property` is set to `maintaining`.

=== Externalizing property on Config Source level

// file 0
microprofile-config.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config-1.properties[]
----

A [hotspot file=0]`microprofile-config.properties` property file has already been created in the `resources/META-INF` directory. This configuration file is the default configuration source for an application that uses MicroProfile Config.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `microprofile-config-maintaining.properties` file.#
`src/main/resources/META-INF/microprofile-config-maintaining.properties`
----

// file 1
microprofile-config-maintaining.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaining1.properties[]
----

Config Profile properties can be used at the Config Source level by providing a config source file under the META-INF folder on the classpath with the name formatted as `microprofile-config-<mp.config.profile>.properties`. With `mp.config.profile` set to `maintaining`, the file [hotspot file=1]`microprofile-config-maintaining.properties` would be loaded be loaded on top of the default config source `microprofile-config.properties` file. In this case, the [hotspot=inventory-inMaintenance file=1]`io_openliberty_guides.inventory_inMaintenance` property from [hotspot file=1]`microprofile-config-maintaining.properties` would take precedence, and thus is set to `true`.

=== Externalizing property on Property level

A configuration property can be used at the property level by setting its name in the format: `%<mp.config.profile>.<original property name>`. Navigate to the [hotspot file=0]`microprofile-config.properties` property file. With `mp.config.profile` set to `maintaining`, retrieving the config value for `io_openliberty_guides.system_inMaintenance` would use the config property [hotspot=system-inMaintenance file=0]`%maintaining.io_openliberty_guides.system_inMaintenance`. The value of the property would resolve to `true`.

Because you started the Liberty server in dev mode at the beginning of this exercise, all the changes were automatically picked up.

Check out the `system` and `inventory` microservices at the following URLs:

* http://localhost:9080/system/properties

* http://localhost:9080/inventory/systems

Because we started the application in the `maintaining` enviroment, the following message displays: `Service is currently in maintenance`.

// =================================================================================================
// Working with Property Expressions
// =================================================================================================
== Working with Property Expressions

The value of a config property may contain an expression corresponding to another config property. Property Expressions provide a way to embed expression segments in property values using the `${}` sequence.

Additionally, you can implement expressions with the following syntax:

* `${prop:default}` - Provides a `default` value after the `:` if the expression doesn't find a value for the property `prop`.

* `${prop${compose}}` - Composed expressions where inner expressions are resolved first.

* `${prop1}${prop2}` - Multiple expressions.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-maintaining.properties` file.#
`src/main/resources/META-INF/microprofile-config-maintaining.properties`
----

// file 0
microprofile-config-maintaining.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaning2.properties[]
----

When looking up the [hotspot=email file=0]`io_openliberty_guides.email` property, the value is expanded to `alice@guides.openliberty.io`.

Try changing the configuration value for property [hotspot=role file=0]`role` in the [hotspot file=0]`microprofile-config-maintaining.properties` file. Your changes are updated dynamically, and you do not need to restart the server. Refresh http://localhost:9080/config to observe the value of property [hotspot=email file=0]`io_openliberty_guides.email` at each change:

* Update the value of property [hotspot=role file=0]`role` to `customerSupport`. The value of `io_openliberty_guides.email` is resolved to `bob@guides.openliberty.io`.

* Update the value of property [hotspot=role file=0]`role` to `foo`. Since property `io_openliberty_guides.foo` does not exist, the deafult value `admin` is used. The value of `io_openliberty_guides.email` is then resolved to `admin@guides.openliberty.io`.

When you are finished trying out changing this configuration, change the value of property [hotspot=role file=0]`role` back to `technicalSupport`.

// =================================================================================================
// Injecting configuration using the ConfigValue metadata object
// =================================================================================================
== Injecting configuration using the ConfigValue metadata object

// file 0
microprofile-config-maintaining.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/resources/META-INF/microprofile-config-maintaning2.properties[]
----

// file 1
bootstrap.properties
[source, properties, linenums, role='code_column']
----
include::finish/src/main/liberty/config/bootstrap.properties[]
----

// file 2
jvm.options
[source, options, linenums, role='code_column']
----
include::finish/src/main/liberty/config/jvm.options[]
----

// file 3
server.env
[source, env, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.env[]
----

// file 4
server.xml
[source, xml, linenums, role='code_column']
----
include::finish/src/main/liberty/config/server.xml[]
----

Note that the `io_openliberty_guides.technical_support` property is defined in multiple different config sources in the application as listed as follows:

Note that the following five config sources all contain the `io_openliberty_guides.technical_support` property:

* [hotspot=tech-support file=0]`microprofile-config-maintaining.properties`

* [hotspot=tech-support file=1]`bootstrap.properties`

* [hotspot=tech-support file=2]`jvm.options`

* [hotspot=tech-support file=3]`server.env`

* [hotspot=tech-support file=4]`server.xml`

To figure out where the value of property `io_openliberty_guides.technical_support` comes from, 

[role="code_command hotspot file=5", subs="quotes"]
----
#Replace the `ConfigResource.java` file.#
`src/main/java/io/openliberty/guides/config/ConfigResource.java`
----

// file 5
ConfigResource.java
[source, java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/config/ConfigResource.java[]
----

The ConfigValue holds additional information after the lookup of a configuration property.

To use the https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/org/eclipse/microprofile/config/ConfigValue.html[ConfigValue API class^], inject the [hotspot=tech-support file=5]`io_openliberty_guides.technical_support` property as usual, only this time define the type as `ConfigValue`.

The `ConfigValue` holds additional information after the lookup of a config property, where you can retrieve with the get methods defined in the https://download.eclipse.org/microprofile/microprofile-config-2.0/apidocs/[Javadoc^].

For example, the [hotspot=getConfigSource file=5]`getConfigSource()` method determines which ConfigSource has the highest ordinal for property `io_openliberty_guides.technical_support` by calling the [hotspot=getSourceName file=5]`getSourceName()` method.

Now point your browser to http://localhost:9080/config/technicalSupport to determine the winning ConfigSource for property `io_openliberty_guides.technical_support`. Try changing the value of property `io_openliberty_guides.technical_support` in the winning ConfigSource and observe the changes at http://localhost:9080/config.

// =================================================================================================
// Injecting multi-valued config property using the Config API
// =================================================================================================
== Injecting multi-valued config property using the Config API



// // =================================================================================================
// // Adding configuration to the service
// // =================================================================================================
// == Adding configuration to the microservice

// To use externalized configuration in the `inventory` service,
// [role="code_command hotspot", subs="quotes"]
// ----
// #Replace the `InventoryResource` class.#
// `src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
// ----
// InventoryResource.java
// [source, Java, linenums, role='code_column hide_tags=copyright']
// ----
// include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[]
// ----
// To add configuration to the `inventory` service, the [hotspot=config-injection file=0]`InventoryConfig` object is injected to the existing class.

// The port number from the configuration is retrieved by the [hotspot=config-port file=0]`inventoryConfig.getPortNumber()` method and passed to the [hotspot=config-port file=0]`manager.get()` method as a parameter.

// To determine whether the inventory service is in maintenance or not (according to the configuration value), [hotspot=isInMaintenance file=0]`inventoryConfig.isInMaintenance()` class method is used. If you set the [hotspot=4 file=1]`io_openliberty_guides_inventory_inMaintenance` property to `true` in the configuration, the inventory service returns the message, `ERROR: Service is currently in maintenance`, along with the contact email. The email configuration value can be obtained by calling [hotspot=getEmail file=0]`inventoryConfig.getEmail()` method.

// CustomConfigSource.json
// [source, Json, linenums, role='code_column']
// ----
// include::finish/resources/CustomConfigSource.json[]
// ----


// // =================================================================================================
// // Building and running the application
// // =================================================================================================

// [role=command]
// include::{common-includes}/devmode-build.adoc[]

// // static guide instructions:
// ifndef::cloud-hosted[]
// While the server is running, the following two microservices should be available to access:

// * http://localhost:9080/system/properties[http://localhost:9080/system/properties^]

// * http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^]


// You can find the service that retrieves configuration information that is specific to this guide at the following location:

// * http://localhost:9080/config[http://localhost:9080/config^]
// endif::[]

// // cloud-hosted guide instructions:
// ifdef::cloud-hosted[]
// While the server is running, run the following curl command to access the ***system*** microservice:
// ```bash
// curl -s http://localhost:9080/system/properties | jq
// ```

// and run the following curl command to access the ***inventory*** microservice:
// ```bash
// curl -s http://localhost:9080/inventory/systems | jq
// ```

// You can find the service that retrieves configuration information that is specific to this guide by running the following curl command:
// ```bash
// curl -s http://localhost:9080/config | jq
// ```
// endif::[]

// The [hotspot=2 file=0]`config_ordinal` value of the custom configuration source is set to [hotspot=2 file=0]`150`. It overrides configuration values of the default [hotspot file=1]`microprofile-config.properties` source, which has a [hotspot=ordinal file=1]`config_ordinal` value of [hotspot=ordinal file=1]`100`.

// CustomConfigSource.json
// [source, Json, linenums, role='code_column']
// ----
// include::finish/resources/CustomConfigSource.json[]
// ----

// microprofile-config.properties
// [source, properties, linenums, role='code_column']
// ----
// include::finish/src/main/resources/META-INF/microprofile-config.properties[]
// ----

// // static guide instructions:
// ifndef::cloud-hosted[]
// Play with this application by changing configuration values for each property in the [hotspot file=0]`resources/CustomConfigSource.json` file. Your changes are added dynamically, and you do not need to restart the server. Refresh http://localhost:9080/config[http://localhost:9080/config^] to see the dynamic changes.

// For example, change [hotspot=4 file=0]`io_openliberty_guides_inventory_inMaintenance` from `false` to `true`, then try to access http://localhost:9080/inventory/systems[http://localhost:9080/inventory/systems^] again. The following message displays: `ERROR: Service is currently in maintenance`.
// endif::[]

// // cloud-hosted guide instructions:
// ifdef::cloud-hosted[]
// Play with this application by changing configuration values for each property in the ***resources/CustomConfigSource.json*** file. Your changes are added dynamically, and you do not need to restart the server. Rerun the following curl command to see the dynamic changes:
// ```bash
// curl -s http://localhost:9080/config | jq
// ```

// For example, change ***io_openliberty_guides_inventory_inMaintenance*** from ***false*** to ***true***, then try to access http://localhost:9080/inventory/systems again by running the following curl command:
// ```bash
// curl -s http://localhost:9080/inventory/systems | jq
// ```

// The following message displays: ***ERROR: Service is currently in maintenance***.
// endif::[]


// // =================================================================================================
// // Testing the application
// // =================================================================================================

// == Testing the application

// [role="code_command hotspot", subs="quotes"]
// ----
// #Create the `ConfigurationIT` class.#
// `src/test/java/it/io/openliberty/guides/config/ConfigurationIT.java`
// ----
// ConfigurationIT.java
// [source, Java, linenums, role='code_column hide_tags=copyright']
// ----
// include::finish/src/test/java/it/io/openliberty/guides/config/ConfigurationIT.java[]
// ----

// microprofile-config.properties
// [source, properties, linenums, role='code_column']
// ----
// include::finish/src/main/resources/META-INF/microprofile-config.properties[]
// ----


// The [hotspot=testInitialServiceStatus file=0]`testInitialServiceStatus()` test case reads the value of the [hotspot=inventory-in-maintenance file=1]`io_openliberty_guides_inventory_inMaintenance` configuration property in the [hotspot file=1]`META-INF/microprofile-config.properties` file and checks the HTTP response of the inventory service. If the configuration value is `false`, the service returns a valid response. Otherwise, the service returns the following message: `ERROR: Service is currently in maintenance`.

// Because the [hotspot=inventory-in-maintenance file=1]`io_openliberty_guides_inventory_inMaintenance` configuration property is set to `false` by default, the [hotspot=testPutServiceInMaintenance file=0]`testPutServiceInMaintenance()` test case first checks that the inventory service is not in maintenance in the beginning. Next, this test switches the value of the [hotspot=inventory-in-maintenance file=1]`io_openliberty_guides_inventory_inMaintenance` configuration property to `true`. In the end, the inventory service returns the following message: `ERROR: Service is currently in maintenance`.

// The [hotspot=testChangeEmail file=0]`testChangeEmail()` test case first puts the `inventory` service in maintenance, then it changes the email address in the configuration file. In the end, the `inventory` service should display the error message with the latest email address.

// In addition, a few endpoint tests have been provided for you to test the basic functionality of the `inventory` and `system` services. If a test failure occurs, then you must have introduced a bug into the code. Remember that you must register the custom configuration source and custom converter in the `src/main/resources/META-INF/services/` directory. If you don't complete these steps, the tests will fail. These tests run automatically as a part of the integration test suite.


// [role=command]
// include::{common-includes}/devmode-test.adoc[]

// You see the following output:

// [source, role="no_copy"]
// ----
// -------------------------------------------------------
//  T E S T S
// -------------------------------------------------------
// Running it.io.openliberty.guides.config.ConfigurationIT
// Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.92 s - in it.io.openliberty.guides.config.ConfigurationIT
// Running it.io.openliberty.guides.system.SystemEndpointIT
// Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 s - in it.io.openliberty.guides.system.SystemEndpointIT
// Running it.io.openliberty.guides.inventory.InventoryEndpointIT
// [WARNING ] Interceptor for {http://client.inventory.guides.openliberty.io/}SystemClient has thrown exception, unwinding now
// Could not send Message.
// [err] The specified host is unknown.
// Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.077 s - in it.io.openliberty.guides.inventory.InventoryEndpointIT

// Results:

// Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
// ----

// The warning and error messages are expected and result from a request to a bad or an unknown hostname. This request is made in the `testUnknownHost()` test from the `InventoryEndpointIT` integration test.

// To see whether the tests detect a failure, remove the configuration resetting line in the [hotspot=setup file=0]`setup()` method of the [hotspot file=0]`ConfigurationIT.java` file. Then, manually change some configuration values in the `resources/CustomConfigSource.json` file. Rerun the tests. You will see a test failure occur.

// [role=command]
// include::{common-includes}/devmode-quit.adoc[]


== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Config in Open Liberty.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]
